/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package hotel.management;

import java.sql.ResultSetMetaData;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author anshu
 */
public class ManageRoom extends javax.swing.JFrame {

    Connection con = null;
    Statement st = null;
    PreparedStatement pst = null;
    ResultSet rs = null;

    /**
     * Creates new form ManageRoom
     */
    public ManageRoom() {
        initComponents();
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/hotels", "root", "sukku@imunni");
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(login.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(login.class.getName()).log(Level.SEVERE, null, ex);
        }
        ShowRecordInTable();
    }

//    public void ShowRecordInTable() {
//        int c = 0;
//        try {
//            pst = con.prepareStatement("select * from room");
//            rs = pst.executeQuery();
//            ResultSetMetaData rand = rs.getMetaData();
//            c = rand.getColumnCount();
//            DefaultTableModel tmodel = (DefaultTableModel) jTable.getModel();
//            tmodel.setRowCount(0);
//            if (!rs.next()) {
//                System.out.println("No data found in the room table."); // Debugging line
//                return; // Exit if no data
//            }
//            while (rs.next()) {
//                Vector column = new Vector();
//                for (int i = 1; i <= c; i++) {
//                    column.add(rs.getString("roomnumber"));
//                    column.add(rs.getString("roomtype"));
//                    column.add(rs.getString("bed"));
//                    column.add(rs.getString("price"));
//                    column.add(rs.getString("status"));
//
//                }
//                tmodel.addRow(column);
    ////                jTable.revalidate();
////                jTable.repaint();
//            }
//
//        } catch (SQLException ex) {
//            Logger.getLogger(ManageRoom.class.getName()).log(Level.SEVERE, null, ex);
//        }
//
//    }
    public void ShowRecordInTable() {
        try {
            pst = con.prepareStatement("SELECT * FROM room"); // Corrected SQL query
            rs = pst.executeQuery();
            DefaultTableModel tmodel = (DefaultTableModel) jTable.getModel();
            tmodel.setRowCount(0); // Clear existing rows

            if (!rs.next()) {
                System.out.println("No data found in the room table."); // Debugging line
                return; // Exit if no data
            }

            do {
                Vector<String> column = new Vector<>();
                column.add(rs.getString("roomnumber"));
                column.add(rs.getString("roomtype"));
                column.add(rs.getString("bed"));
                column.add(rs.getString("price"));
                column.add(rs.getString("status"));
                tmodel.addRow(column);
            } while (rs.next());

        } catch (SQLException ex) {
            Logger.getLogger(ManageRoom.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtroomno = new javax.swing.JTextField();
        jComboBoxroomtype = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtprice = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jComboBoxbed = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1280, 670));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Sitka Text", 3, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hotel/management/manage.png"))); // NOI18N
        jLabel1.setText("Manage Room");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 24, 188, 54));

        jTable.setFont(new java.awt.Font("Sitka Text", 3, 14)); // NOI18N
        jTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Room Number", "Room Type", "Bed Type", "Price", "Status"
            }
        ));
        jScrollPane1.setViewportView(jTable);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 111, 1160, 320));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hotel/management/close.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1215, 0, 55, 41));

        jLabel2.setFont(new java.awt.Font("Sitka Text", 3, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Room Number");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 465, 146, -1));

        jLabel3.setFont(new java.awt.Font("Sitka Text", 3, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Room Type");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(453, 464, 141, 24));

        txtroomno.setFont(new java.awt.Font("Sitka Text", 3, 18)); // NOI18N
        getContentPane().add(txtroomno, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 494, 175, 37));

        jComboBoxroomtype.setFont(new java.awt.Font("Sitka Text", 3, 18)); // NOI18N
        jComboBoxroomtype.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AC", "Non-AC" }));
        jComboBoxroomtype.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxroomtypeActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBoxroomtype, new org.netbeans.lib.awtextra.AbsoluteConstraints(453, 495, 170, 38));

        jLabel4.setFont(new java.awt.Font("Sitka Text", 3, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Bed");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 550, 73, 34));

        jLabel5.setFont(new java.awt.Font("Sitka Text", 3, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Price");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 550, 90, 40));

        txtprice.setFont(new java.awt.Font("Sitka Text", 3, 18)); // NOI18N
        txtprice.setActionCommand("<Not Set>");
        txtprice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpriceActionPerformed(evt);
            }
        });
        getContentPane().add(txtprice, new org.netbeans.lib.awtextra.AbsoluteConstraints(453, 590, 170, 38));

        jButton2.setFont(new java.awt.Font("Snap ITC", 3, 18)); // NOI18N
        jButton2.setText("Add Room Details");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(878, 520, -1, 49));

        jComboBoxbed.setFont(new java.awt.Font("Sitka Text", 3, 18)); // NOI18N
        jComboBoxbed.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Single", "Double" }));
        getContentPane().add(jComboBoxbed, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 588, 175, 46));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hotel/management/back.jpg"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1270, 680));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBoxroomtypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxroomtypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxroomtypeActionPerformed

    private void txtpriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpriceActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        if (txtroomno.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "All field should be filled");
            txtroomno.requestFocus();
        } else if (txtprice.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "All field should be filled");
            txtprice.requestFocus();
        } else {
            try {
                pst = con.prepareStatement("SELECT * FROM room where roomnumber=?");
                pst.setString(1, txtroomno.getText());
                rs = pst.executeQuery();
                if (rs.next()) {
                    JOptionPane.showMessageDialog(this, "Already Allocated this Room number");
                } else {
                    pst = con.prepareStatement("INSERT INTO room (roomnumber, roomtype, bed, price, status) VALUES (?,?,?,?,?)");
                    pst.setString(1, txtroomno.getText());
                    pst.setString(2, jComboBoxroomtype.getItemAt(jComboBoxroomtype.getSelectedIndex()));
                    pst.setString(3, jComboBoxbed.getItemAt(jComboBoxbed.getSelectedIndex()));
                    pst.setString(4, txtprice.getText());
                    pst.setString(5, "Not Booked");
                    pst.executeUpdate();
                    JOptionPane.showMessageDialog(this, "Room Added");
                    ShowRecordInTable();
                    txtroomno.setText("");
                    txtprice.setText("");

                }

            } catch (SQLException ex) {
                Logger.getLogger(ManageRoom.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManageRoom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManageRoom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManageRoom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManageRoom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManageRoom().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBoxbed;
    private javax.swing.JComboBox<String> jComboBoxroomtype;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable;
    private javax.swing.JTextField txtprice;
    private javax.swing.JTextField txtroomno;
    // End of variables declaration//GEN-END:variables
}
